package examples.distributed_programming.corba;

/**
 * SDS_Server.java Generated by the IDL-to-Java compiler (portable), version
 * "3.0" from SDS_Server.idl Mittwoch, 27. Juni 2001 19.08 Uhr GMT+02:00
 */

public interface SDS_Server extends SDS_ServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
} // interface SDS_Server
