package examples.distributed_programming.corba;

/**
 * SDS_ServerHolder.java Generated by the IDL-to-Java compiler (portable),
 * version "3.0" from SDS_Server.idl Mittwoch, 27. Juni 2001 19.08 Uhr GMT+02:00
 */

public final class SDS_ServerHolder implements org.omg.CORBA.portable.Streamable {
    public SDS_Server value = null;

    public SDS_ServerHolder() {
    }

    public SDS_ServerHolder(SDS_Server initialValue) {
        value = initialValue;
    }

    @Override
    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = SDS_ServerHelper.read(i);
    }

    @Override
    public void _write(org.omg.CORBA.portable.OutputStream o) {
        SDS_ServerHelper.write(o, value);
    }

    @Override
    public org.omg.CORBA.TypeCode _type() {
        return SDS_ServerHelper.type();
    }

}
