package examples.distributed_programming.corba.serverPackage;

/**
 * SDS_ServerPackage/ReplyHolder.java Generated by the IDL-to-Java compiler
 * (portable), version "3.0" from SDS_Server.idl Mittwoch, 27. Juni 2001 19.08
 * Uhr GMT+02:00
 */

public final class ReplyHolder implements org.omg.CORBA.portable.Streamable {
    public Reply value = null;

    public ReplyHolder() {
    }

    public ReplyHolder(Reply initialValue) {
        value = initialValue;
    }

    @Override
    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = ReplyHelper.read(i);
    }

    @Override
    public void _write(org.omg.CORBA.portable.OutputStream o) {
        ReplyHelper.write(o, value);
    }

    @Override
    public org.omg.CORBA.TypeCode _type() {
        return ReplyHelper.type();
    }

}
