package examples.distributed_programming.corba.serverPackage;

/**
 * SDS_ServerPackage/Reply.java Generated by the IDL-to-Java compiler
 * (portable), version "3.0" from SDS_Server.idl Mittwoch, 27. Juni 2001 19.08
 * Uhr GMT+02:00
 */

public final class Reply implements org.omg.CORBA.portable.IDLEntity {
    public final static int NOT_FOUND = 0;
    public final static int FOUND = 1;

    public int status = NOT_FOUND;
    public String name = "";
    public String vorname = "";
    public int personalnummer = 0;
    public String wohnort = "";

    public Reply() {
    } // ctor

    public Reply(int _status, String _name, String _vorname, int _personalnummer, String _wohnort) {
        status = _status;
        name = _name;
        vorname = _vorname;
        personalnummer = _personalnummer;
        wohnort = _wohnort;
    } // ctor

} // class Reply
